# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c2a380e0e9742b31674c8118406b1e1f8fd2c5c380304e38de4ec61c8fb25737902701f78cb7d439ee3b3586666fb625f8be561d3ee3d2632468e7a8dedbe95

test:
  secret_key_base: 12ce4215d2068a2a4da1aed30fb829bef7c45f88ee584b6f336ab7a3d1a4cd7d8188ce3387e5da14ad0a1603a0743ba548c235e51c42f66dbf8aeb632202a9f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
